services:
  nginx:
    image: nginx:stable-alpine
    container_name: messenger_nginx
    ports:
      - "82:80"
    volumes:
      - ./front:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    command: ["nginx", "-g", "daemon off;"]
    restart: always
    depends_on:
      - back

  back:
    build:
      context: .
      dockerfile: back/Dockerfile
    container_name: messenger_back
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/messenger

    ports:
      - "8002:8000"
    depends_on:
      - db
      

  db:
    image: postgres:16
    container_name: messenger_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: messenger
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
